# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

#on: manual
#  push:
#    branches: [ "branch2" ]
#  pull_request:
#    branches: [ "branch2" ]

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - qa
          - prod
        description: Deployment environment
      space:
        type: choice
        options:
          - synthetic
          - actual
        description: Deployment environment

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
#    - name: Build wheel and install
#      run: |
#        python -m pip install --user --upgrade build
#        python -m build
#        #pip install .
#        find ./dist/*.whl | xargs pip install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
    - name: Execute python file
      run: python main3.py