name: QA validation workflow deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - qa
          - prod
        description: Deployment environment
      space:
        type: choice
        options:
          - synthetic
          - actual
        description: Deployment environment
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute python file
        run: python Test_Validation/Contact_info_Raw2Bronze_validation.py